version: '3'

services:
  sdns-proxy:
    build: './sdns-proxy'
    network_mode: "host"
    ports:
      - 127.0.0.1:53:53
  udp-proxy:
    build: './udp-proxy'
    network_mode: "host"
    ports:
      - 127.0.0.1:53:53/udp
